import './globals.css';
import Header from '@/components/Home/Header';
import Footer from '@/components/Home/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-white'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
